<?php
error_reporting(E_ALL); 
ini_set('display_errors','1');
 
 $DEBUG = 0;
 /*define("url","http://naw1.posios.com");
define("companyId", 31185);
define("deviceId", "api");
define("password", "SteveK26");
define("username", "steve@stevekemph.com");*/

define("url", "http://staging-exact-integration.posios.com");
define("companyId", 14431);
define("deviceId", "api");
define("password", "bK6Vre2QtGZdZ5q7");
define("username", "staging@stevekemph.com");
//************************************************
//********** GET TOKEN ***************************
//************************************************
function _lightspeed_restaurant_get_token(){
global $DEBUG;
//$DEBUG =0;
$params = array("companyId"=>companyId,
				"deviceId" =>deviceId,
				"password" =>password,
				"username" =>username
				);

//$data_string =   "companyId".trim($params[0])."&deviceId=".trim($params[1])."&password=".trim($params[2])."&username=".trim($params[3]);
$data_string = json_encode($params);

//GET TOKEN
if($DEBUG==1)print_r($data_string);
$uri = url . "/PosServer/rest/token";
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL,$uri);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS,$data_string);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
'Content-Type: application/json',
'Accept: */*',
'Content-Length: ' . strlen($data_string))
); 
$result = curl_exec($ch);
//$result = json_decode($result, true);
//Get Access Token on Successful Setup & Initialization of the User
if($DEBUG==1)print_r($result);
$result = json_decode($result,true);
if($DEBUG==1)print_r($result);
$access_token = $result['token'];
if($DEBUG==1)echo("<br>ACCESS TOKEN:". $access_token);
echo "<br><br>";
curl_close($ch);
return $access_token;
}


//************************************************
//*********** CREATE CUSTOMER ********************
//************************************************
function _lightspeed_restaurant_create_customer($token, $values){
global /*$companyId,$deviceId,$password,$username,*/$DEBUG;

//$DEBUG =0;
$params = array(/*
  "city"=> "New York",
  "companyId" => $companyId,
  "country" => "USA",
  "credits" => 0,
  "customerCards" => array(    
      "code"=> "",
      "companyId"=> $companyId,
      "creationUserId"=> 0,
      "customerId"=> 0,
      "expiryDate"=> 0,
      "generatedDate"=> 0,
      "lastUsedDate"=> 0,
      "lastValueAddedDate"=> 0,
      "originalValue"=> 0,
      "remainingValue"=> 0,
      "type"=> "string",
      "uuid"=> "string"
    ),
  "deliveryCity"=> "New York",
  "deliveryCountry"=> "USA",
  "deliveryStreet"=> "73ST",
  "deliveryStreetNumber"=> "234",
  "deliveryZip"=> "1001",
  "email"=> "ramsesiden@yahoo.com",
  "firstName"=> "Omar",
  "id"=> 0123456789,
  "lastName"=> "Zorrilla",
  "modificationTime"=> "string",
  "note"=> "string",
  "street"=> "string",
  "streetNumber"=> "string",
  "telephone"=> "01122334455",
  "uuid"=> "string",
  "vatNumber"=> "string",
  "zip"=> "10001"
);
*/

  "city"=>  empty($values['city'])?"Illinois":$values['city'],//"New York",
  "country"=> empty($values['country'])?"USA":$values['country'],// "USA",
  "deliveryCity"=> empty($values['delCity'])?"Illinois":$values['delCity'],//"Manhatan",
  "deliveryCountry"=> empty($values['delCountry'])?"USA":$values['delCountry'],//"USA",
  "deliveryStreet"=> empty($values['delStreet'])?"":$values['delStreet'],//"11ST",
  "deliveryStreetNumber"=> empty($values['delStreetNo'])?"":$values['delStreetNo'],//"2",
  "deliveryZip"=> empty($values['delZip'])?"":$values['delZip'],//"10001",
  "email"=> $values['email'],//"ramsesiden@test14.com",
  "firstName"=> $values['fname'],//"test1",
  "lastName"=> $values['lname'],//"testlast1",
  "street"=> empty($values['street'])?"":$values['street'],//"Eleven street",
  "streetNumber"=> empty($values['stNo'])?"":$values['stNo'],//"3",
  "telephone"=> empty($values['phone'])?"":$values['phone'],//"123456789",
  "zip"=> empty($values['zip'])?"":$values['zip'],//"10001"
);

//$data_string =   "companyId".trim($params[0])."&deviceId=".trim($params[1])."&password=".trim($params[2])."&username=".trim($params[3]);
$data_string = json_encode($params);

//CREATE CUSTOMER
if($DEBUG==1)print_r($data_string);
$uri = url . "/PosServer/rest/core/customer";
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL,$uri);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS,$data_string);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
'Content-Type: application/json',
'Accept: */*',
'X-Auth-Token:'. $token,
'Content-Length: ' . strlen($data_string))
); 
$result = curl_exec($ch);
if($DEBUG==1)print_r($result);
echo "<br><br>";
$result = json_decode($result,true);
if($DEBUG==1)print_r($result);
$customer_id = $result;
if($DEBUG==1)echo("<br>CUSTOMER ID:". $customer_id);
curl_close($ch);
return $customer_id;
}

//************************************************
//********** CREATE RESERVATION ******************
//************************************************
function _lightspeed_restaurant_create_reservation($token,$cid,$reserv){
global $DEBUG;

//$DEBUG =0;
//status = {CANCELLED, SEATED, UNKNOWN, ON_HOLD, TO_CHECK, CONFIRMED}
//Formats for endTime and starTime are not ok
$params = array(
  "companyId" =>companyId,
  "customerId"=> $cid,
  "endTime"=> $reserv['date_end'],//"2017-03-24T14:00:00Z",
  "floorId"=> 1,
  "id"=> 1,
  "notes"=> $reserv['message'],//"Reserve this table for me",
  "reservationName"=> $reserv['name'],//"New Reservation",
  "seats"=> $reserv['party_size'],//2,
  "startTime"=> $reserv['date'],//"2017-03-24T13:00:00Z",
  "status"=> "CONFIRMED",//"TO_CHECK",
  "tableId"=> "1",
  "telephone"=> $reserv['phone'],//"33333333"
);
$data_string = json_encode($params);

if($DEBUG==1)print_r($data_string);
$uri = url . "/PosServer/rest/reservation";
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL,$uri);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS,$data_string);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
'Content-Type: application/json',
'Accept: */*',
'X-Auth-Token:'. $token,
'Content-Length: ' . strlen($data_string))
); 
$result = curl_exec($ch);
//$result = json_decode($result, true);
//Get Access Token on Successful Setup & Initialization of the User
if($DEBUG==1)print_r($result);
$result = json_decode($result,true);
if($DEBUG==1)print_r($result);
$reservation_id = $result;
if($DEBUG==1)echo("<br>Reservation Number:". $reservation_id);
echo "<br><br>";
curl_close($ch);
return $reservation_id;
}

//************************************************
//********* CREATE PRODUCT ***********************doesnt work
//************************************************
function _lightspeed_restaurant_create_product($token,$gid){
global $DEBUG;
$gid = 1;

$params = array(
  "additions"=>
    array(
      "displayName" => "Irish Egg Rolls",
      "id"=> 1,
      "maxSelectedAmount"=> 8.25,
      "minSelectedAmount"=> 8.25,
      "multiselect"=> true,
      "name"=> "Irish Egg Rolls",
      "values"=>
       array(
          "id"=> 1,
          "info"=> "Corned beef cabbage and cheese fried in a wonton",
          "modifierId"=> 0,
          "name"=> "Irish Egg Rolls",
          "price"=> 8.25,
          "priceWithoutVAT"=> 8
        )
    ),
  "deliveryPrice"=> 9,
  "deliveryPriceWithoutVat"=> 8.7,
  "deliveryTaxClass"=> "VAT",
  "groupIds"=> array(
    1
  ),
  "id"=> 1,
  "imageLocation"=> "",
  "info"=> "Corned beef cabbage and cheese fried in a wonton",
  "name"=> "Irish Egg Rolls",
  "price"=> 8.25,
  "priceWithoutVat"=> 8,
  "productType"=> "Appetizers",
  "sequence"=> 0,
  "sku"=> "0c54a",
  "stockAmount"=> 1,
  "takeawayPrice"=> 0,
  "takeawayPriceWithoutVat"=> 8,
  "takeawayTaxClass"=> "Taxaway",
  "taxClass"=> "Tax",
  "visible"=> true
);
$data_string = json_encode($params);

if($DEBUG==1)print_r($data_string);
$uri = url . "/PosServer/rest/inventory/productgroup/".$gid."/product";
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL,$uri);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS,$data_string);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
'Content-Type: application/json',
'Accept: */*',
'X-Auth-Token:'. $token,
'id:'.$gid,
'Content-Length: ' . strlen($data_string))
); 
$result = curl_exec($ch);
//$result = json_decode($result, true);
//Get Access Token on Successful Setup & Initialization of the User
if($DEBUG==1)print_r($result);
$result = json_decode($result,true);
if($DEBUG==1)print_r($result);
/*$reservation_id = $result;
if($DEBUG==1)echo("<br>Reservation Number:". $reservation_id);
echo "<br><br>";
curl_close($ch);
return $reservation_id;*/
}


//************************************************
//********** CREATE ORDER ************************
//************************************************
function _lightspeed_restaurant_create_order($token,$cid,$ordered_items){
global $DEBUG;

$now = new DateTime('NOW');
//$now->format('Y-m-d H:i'); 
$now->format('c'); 
//$now->->format(DateTime::ISO8601);
$in_an_hour = clone $now;    
$in_an_hour->modify( '+1 hour' );
$params = 
array (
  'companyId' => companyId,
  'customerId' => $cid,
  'type' => 'takeaway',
  'creationDate' => $now->format('c'),//2017-04-21T01:04:25-06:00,
  'deliveryDate' => $in_an_hour->format('c'),//'2017-04-22T00:49:00-04:00',
  'status' => 'ACCEPTED',
  'description' => 'YPDine OO',
  'orderItems' => $ordered_items,
  /*array (
    0 => 
    array (
      'productId' => 137050,
      'amount' => 1,
      'totalPrice' => 13.56,
      'totalPriceWithoutVat' => 12,
      'unitPrice' => 6.78,
      'unitPriceWithoutVat' => 6,
      'modifiers' => 
      array (
        0 => 
        array (
          'modifierId' => 1830,
          'modifierValueId' => 5947,
          'description' => 'Cheese',
          'modifierName' => 'Cheese',
          'price' => 3.39,
          'priceWithoutVat' => 3,
        ),
        1 => 
        array (
          'modifierId' => 1830,
          'modifierValueId' => 5948,
          'description' => 'Cheese',
          'modifierName' => 'Cheese',
          'price' => 3.39,
          'priceWithoutVat' => 3,
        ),
      ),
    ),
    1 => 
    array (
      'productId' => 137050,
      'amount' => 1,
      'totalPrice' => 5.65,
      'totalPriceWithoutVat' => 5,
      'unitPrice' => 5.65,
      'unitPriceWithoutVat' => 5,
    ),
  ),*/
 /* 'orderPayment' => 
  array (
    'amount' => 1,
    'paymentTypeId' => 4138,
    'paymentTypeTypeId' => 1,
  ),*/
  'orderTaxInfo' => 
  array (
    0 => 
    array (
      'tax' => 0.13,
      'taxRate' => 0.13,
      'totalWithTax' => 24.85,
      'totalWithoutTax' => 22,
    ),
  ),
);


$data_string = json_encode($params);

//GET TOKEN
if($DEBUG==1)print_r($data_string);
$uri = url . "/PosServer/rest/onlineordering/customer/".$cid."/establishmentorder";
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL,$uri);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS,$data_string);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
'Content-Type: application/json',
'Accept: */*',
'X-Auth-Token:'. $token,
'customer'. $cid,
'Content-Length: ' . strlen($data_string))
); 
$result = curl_exec($ch);
//$result = json_decode($result, true);
//Get Access Token on Successful Setup & Initialization of the User
if($DEBUG==1)print_r($result);
$result = json_decode($result,true);
if($DEBUG==1)print_r($result);

if($DEBUG==1)echo("<br>ORDER:". $order);
curl_close($ch);

$filename = '/tmp/data.txt';
// var_dump
ob_start();
var_dump($result);
$debug_dump = ob_get_clean();
//$debug_dump = var_export($result, true);
try{ 
$file = fopen($filename, "w");
fwrite($file, $debug_dump. PHP_EOL);
fwrite($file, "".$params['creationDate'] .  PHP_EOL);
fclose($file);
} catch(Exception $e) {
       echo("Error :". $e->getMessage());
}


return $result;
}


//************************************************
//    Function Get Products
//************************************************

function _lightspeed_restaurant_get_products($token){
global $DEBUG;

$uri = url . "/PosServer/rest/inventory/product";
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL,$uri);
//curl_setopt($ch, CURLOPT_POST, 1);
//curl_setopt($ch, CURLOPT_POSTFIELDS,$data_string);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
'Content-Type: application/json',
'Accept: */*',
'X-Auth-Token:'. $token,
//'customer'. $cid,
//'Content-Length: ' . strlen($data_string)
)
); 
$result = curl_exec($ch);
$result = json_decode($result,true);
if($DEBUG==1)print_r($result);
//if($DEBUG==1)echo("<br>ACCESS TOKEN:". $access_token);
curl_close($ch);

return $result;

}


//************************************************
//    Function Get CUSTOMER
//************************************************
function _lightspeed_restaurant_get_customer($token,$email){
global $DEBUG;

$uri = url . "/PosServer/rest/onlineordering/customer?email=".urlencode($email);
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL,$uri);
//curl_setopt($ch, CURLOPT_POST, 1);
//curl_setopt($ch, CURLOPT_POSTFIELDS,$data_string);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
'Content-Type: application/json',
'Accept: */*',
'X-Auth-Token:'. $token,
//'email:'.$email,
//'customer'. $cid,
//'Content-Length: ' . strlen($data_string)
)
); 
$result = curl_exec($ch);
$result = json_decode($result,true);
if($DEBUG==1)print_r($result);
//if($DEBUG==1)echo("<br>ACCESS TOKEN:". $access_token);
curl_close($ch);

return $result;

//RPTA
/*
 {
  "results": [
    {
      "id": 32051,
      "uuid": "baa86ae1092c11e7a47f065ba9dd3bcf",
      "firstName": "Omar",
      "lastName": "Zorrilla Llerena",
      "street": "Eleven street",
      "streetNumber": "3",
      "zip": "10001",
      "city": "New York",
      "country": "USA",
      "telephone": "123456789",
      "deliveryStreet": "11ST",
      "deliveryStreetNumber": "2",
      "deliveryZip": "10001",
      "deliveryCity": "Manhatan",
      "deliveryCountry": "USA",
      "email": "omar@ramsesiden.net",
      "credits": 0,
      "companyId": 14431,
      "modificationTime": "2017-04-23T18:42:30.443Z",
      "note": "",
      "vatNumber": "",
      "dateOfBirth": "",
      "language": "",
      "customerCards": []
    }
  ],
  "amount": 0,
  "offset": 50,
  "total": 1
}
*/
}
//************************************************
//    HOOK  
//************************************************/
function lightspeed_restaurant_commerce_checkout_complete($order){
$ordered_items=array();

/********************** GET CUSTOMER DATA ****************************************/
        $query = db_select('temp', 'n')
        ->fields('n', array('data'))
        ->condition('order_id',  $order->order_id,'=');
        $result = $query->execute();
        $customer = json_decode($result->fetchField(),true);

/********************** GET LIGHTSPEED PRODUCT ID ****************************************/
    for($i=0;$i<count($order->commerce_line_items['und']);$i++){// as $key => $line_item_wrapper) {
      //$line_item = $line_item_wrapper->value();
        $query = db_select('field_data_commerce_product', 'n')
        ->fields('n', array('commerce_product_product_id'))
        ->condition('entity_id',  $order->commerce_line_items['und'][$i]['line_item_id'],'=');
        $result = $query->execute();
        $pid = $result->fetchField();
      
        $query = db_select('field_data_field_menu_variants', 'n')
        ->fields('n', array('entity_id'))
        ->condition('field_menu_variants_product_id', $pid,'=');
        $result = $query->execute();
        $nid = $result->fetchField();
        
        $query = db_select('field_data_field_lightspeed_code', 'n')
        ->fields('n', array('field_lightspeed_code_value'))
        ->condition('entity_id', $nid,'=');
        $result = $query->execute();
        $ligthspeed_product_id= $result->fetchField();

    /********************** GET UNIT PRICE ****************************************/
        $query = db_select('field_data_commerce_unit_price', 'n')
        ->fields('n', array('commerce_unit_price_amount'))
        ->condition('entity_id',  $order->commerce_line_items['und'][$i]['line_item_id'],'=');
        $result = $query->execute();
        $unit_price = $result->fetchField()/100;
    /********************** GET UNIT QUANTITY ****************************************/
        $query = db_select('commerce_line_item', 'n')
        ->fields('n', array('quantity'))
        ->condition('line_item_id',  $order->commerce_line_items['und'][$i]['line_item_id'],'=');
        $result = $query->execute();
        $unit_quantity = $result->fetchField();    
     /********************** GET CART QUANTITY AND TOTALS ****************************************/
    $wrapper = entity_metadata_wrapper('commerce_order', $order);
    $line_items = $wrapper->commerce_line_items;
    $quantity = commerce_line_items_quantity($line_items, commerce_product_line_item_types());
    $total = commerce_line_items_total($line_items);
     /********************** GET CART CURRENCY AND TOTALS ****************************************/ 
     $currency = commerce_currency_load(commerce_default_currency());
     $product_price_total = commerce_currency_format($total['amount'], $total['currency_code']); 
      
      $sides_per_product=array();
      $sides_per_product = get_sides_per_product($order->commerce_line_items['und'][$i]['line_item_id']);
        
      $tok = _lightspeed_restaurant_get_token();
  
      if(!empty($sides_per_product)){      
        //if(count($sides_per_product)==intval($unit_quantity)){
            foreach($sides_per_product as $key => $spp){
                $spp_with_attributes = sides_to_modifiers($sides_per_product[$key],$ligthspeed_product_id,$tok);
                
                $temp =  array (
                'productId' => $ligthspeed_product_id,
                'amount' => intval($unit_quantity)/count($sides_per_product),
                'totalPrice' => $total['amount']/100,
                'totalPriceWithoutVat' =>$total['amount']/100,
                'unitPrice' => floatval($unit_price),///count($sides_per_product),
                'unitPriceWithoutVat' => floatval($unit_price),///count($sides_per_product),
                'modifiers' => array($spp_with_attributes),
                 );
                  //array_push($temp,$spp_with_attributes);////here it is the modifier
                 array_push($ordered_items,$temp);
          
            }
        //}elseif(count($sides_per_product)<intval($unit_quantity)){
            
        //}    
      }else{
            $temp =  array (
            'productId' => $ligthspeed_product_id,
            'amount' => intval($unit_quantity),
            'totalPrice' => $total['amount']/100,
            'totalPriceWithoutVat' =>$total['amount']/100,
            'unitPrice' => floatval($unit_price),///count($sides_per_product),
            'unitPriceWithoutVat' => floatval($unit_price),///count($sides_per_product),
             );
              //array_push($temp,$spp_with_attributes);////here it is the modifier
             array_push($ordered_items,$temp);
      }  
        
        
    }

//MAIN CODE
//$cid = '32049';//52';//create_customer($tok);
//get_products($tok);
//create_product($tok,1);
//create_reservation($tok,$cid);
 if(user_is_anonymous()){
    $res = _lightspeed_restaurant_get_customer($tok,trim($customer['email']));
    $values['fname'] = "".$customer['name'];
    $values['lname'] = "".$customer['lastname'];
   // $values['phone'] = "".$customer['phone'];
    $values['email'] = "".$customer['email'];
    if(empty($res['results'])){
          $cid = _lightspeed_restaurant_create_customer($tok, $values);
    }else{
          $cid = $res['results'][0]['id']; 
    }
  }elseif(user_is_logged_in()){
    global $user;
    $user_full = user_load($user->uid); // user_load(uid) returns the complete array
    $res = _lightspeed_restaurant_get_customer($tok,trim($user->mail));
    $values['fname'] = "".$user_full->field_given_name['und'][0]['value'];
    $values['lname'] = "".$user_full->field_lastname['und'][0]['value'];
    $values['phone'] = "".$user_full->field_telephone['und'][0]['value'];
    $values['email'] = "".$user->mail;
    if(empty($res['results'])){
          $cid = _lightspeed_restaurant_create_customer($tok, $values);
    }else{
          $cid = $res['results'][0]['id']; 
    }
    
  }

 $resultado = _lightspeed_restaurant_create_order($tok,$cid,$ordered_items);
 //return $resultado;
}
/*****************************************************************************/
function   _lightspeed_restaurant_save_on_temp($values){
global $user;
$uid = $user->uid;  
$order_id = commerce_cart_order_id($uid);

        $query = db_select('temp', 'n')
        ->fields('n', array('order_id'))
        ->condition('order_id',  $order_id,'=');
        $result = $query->execute();
        $orden = $result->fetchField();
if(empty($orden)){
 $query =    db_insert('temp')
->fields(array(
  'order_id' => $order_id,
  'data' => json_encode($values),
  //'created' => REQUEST_TIME,
))
->execute();
 }   
}

/*****************************************************************************/

function get_sides_per_product($line_item_id){
    $sidespp=array();
        $query = db_select('commerce_line_item', 'n')
        ->fields('n', array('side'))
        ->condition('line_item_id',  $line_item_id,'=');
        $result = $query->execute();
        $sidespp = json_decode($result->fetchField());
    
    return $sidespp;
}
/*****************************************************************************/
function sides_to_modifiers($spp,$prod_id,$tok){
    $mod_id='';
    $prod_with_modifiers =  get_modifiers($tok,$prod_id);
    $only_modifiers = $prod_with_modifiers['additions'][0]['values'];
    $modv_id = $prod_with_modifiers['additions'][0]['id'];
    foreach($only_modifiers as $key => $value){
        if(strcasecmp(urldecode($spp), $only_modifiers[$key]['info']) == 0){
           $mod_id =  $only_modifiers[$key]['id'];break;
        }
    }
    
    $modifier = array(
          'modifierId' => $mod_id,
          'modifierValueId' => $modv_id,
          'description' => urldecode($spp),
          'modifierName' => urldecode($spp),
          'price' => 0.00,
          'priceWithoutVat' => 0.00,
        );
  return $modifier;
}


//************************************************
//    Function Get Modifiers
//************************************************

function get_modifiers($token,$prodid){
global $companyId,$deviceId,$password,$username,$DEBUG;

$uri = url . "/PosServer/rest/inventory/product/".$prodid;//".$id."/product";
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL,$uri);
//curl_setopt($ch, CURLOPT_POST, 1);
//curl_setopt($ch, CURLOPT_POSTFIELDS,$data_string);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
'Content-Type: application/json',
'Accept: */*',
'X-Auth-Token:'. $token,
//'customer'. $cid,
//'Content-Length: ' . strlen($data_string)
)
); 
$result = curl_exec($ch);
//$result = json_decode($result, true);
//Get Access Token on Successful Setup & Initialization of the User
//if($DEBUG==1)print_r($result);
$result = json_decode($result,true);
curl_close($ch);
return $result;

}